services:
  db-dev:
      image: postgres:13
      container_name: db-dev
      restart: always
      ports:
        - 2345:5432
      env_file:
        - .env.dev 
      environment:
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - postgres-data:/var/lib/postgresql/data

  api-dev:
      container_name: api-dev
      build: 
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - 5000:5000
      depends_on:
        - db-dev
      env_file:
        - .env.dev
      environment:
        DATABASE_URL: ${DATABASE_URL}
volumes:
    postgres-data: