services:
  db:
      image: postgres:13
      container_name: db
      restart: always
      ports:
        - 2345:5432
      env_file:
        - .env 
      environment:
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - postgres-data:/var/lib/postgresql/data

  api:
      container_name: api
      build: .
      ports:
        - 5000:5000
      depends_on:
        - db 
      env_file:
        - .env 
      environment:
        DATABASE_URL: ${DATABASE_URL}
volumes:
    postgres-data:
  